### ISSUE TITLE
Great job specifying prices 

### ISSUE THREAD

**Issue by sangjunp4rk** [WennDann/prj-rev-bwfs-dasmoto#2]
Good job specifying the em css selector id and good choice of name. Clear and concise names are the best. This gives you more flexibility as your code grows in size and makes your code more reusable since if you need to do similar highlighting in the future, you can just reference this again.

https://github.com/WennDann/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsCrafts/index.html#L14

**Comment by WennDann** [comment]
@sangjunp4rk Thanks, I'll try to keep it that way with the names.
