### ISSUE TITLE
Keep lines short

### ISSUE THREAD

**Issue by sangjunp4rk** [WennDann/prj-rev-bwfs-dasmoto#4]
Your lines are a bit long right now. Try splitting this into new lines so it's easier to read on one screen without scrolling. Convention is usually ~79-100 characters per line.

https://github.com/WennDann/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsCrafts/index.html#L14

**Comment by WennDann** [comment]
@sangjunp4rk Thanks, I'll keep that in mind for my future projects. Very good point I didn't think of yet, since the project was so small. And I can see where it could lead with some more text in there.
